### ISSUE TITLE
Include isort in pre-commit hooks

### ISSUE THREAD

**Issue by TobiHobi** [ThorbenJensen/blueprint-python#3]
For automated sorting of thirdparty imports
https://github.com/asottile/seed-isort-config

**Comment by top-on** [comment]
@TobiHobi 
sounds like a good feature.
especially because (if I get this correcly) it would not cause the commit to fail, but only make imports cleaner.

**Comment by TobiHobi** [comment]
No fail, but isort is altering/changing the .py files.
Similar behaviour as black
