### ISSUE TITLE
enhance isort by seed-isort-config

### ISSUE THREAD

**Issue by TobiHobi** [ThorbenJensen/blueprint-python#5]
dont know if necessary; https://github.com/asottile/seed-isort-config
enhancement of #3

example implementation in 3_seed-isort-config_importsorting branch

**Comment by top-on** [comment]
@TobiHobi 
thx, i'll check it out.
in the meantime, would you mind opening a draft PR for easier review on a browser?

**Comment by TobiHobi** [comment]
done @ThorbenJensen
